<?php

namespace Portotech\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SentimentscaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentimentscaleRepository extends EntityRepository
{
}
